export const SET_LOADED = 'sos/OrgPage/SET_LOADED'
export const MODAL_STATE = 'sos/OrgPage/MODAL_STATE'
export const ON_CHANGE_VALUE = 'sos/OrgPage/ON_CHANGE_VALUE'
export const ON_HANDLE_MAP_CLICK = 'sos/OrgPage/ON_HANDLE_MAP_CLICK'
export const ON_MATRIX_CHANGE = 'sos/OrgPage/ON_MATRIX_CHANGE'
